# .github/workflows/ci.yml

name: CI (Docker) - unit-tests-base-main # Nome específico para o projeto

on:
  push:
    branches: ["main"]
    paths:
      - "unit-tests-base-main/**" # <-- SÓ RODA se houver alteração nesta pasta

  pull_request:
    branches: ["main"]
    paths:
      - "unit-tests-base-main/**" # <-- SÓ RODA se houver alteração nesta pasta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Define o diretório de trabalho para todos os passos deste job
    defaults:
      run:
        working-directory: ./unit-tests-base-main # <-- DIRETÓRIO DO SEU PROJETO

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dos contêineres
        # Este comando agora será executado de dentro da pasta 'unit-tests-base-main'
        run: docker compose -f docker-compose.test.yml build

      - name: Subir contêineres e executar testes
        run: docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from node-test

      - name: Rodar Linter
        run: docker compose -f docker-compose.test.yml run --rm node-test npm run lint

      - name: Compilar o código TypeScript (Build)
        run: docker compose -f docker-compose.test.yml run --rm node-test npm run build

      - name: Upload do relatório de cobertura
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-unit-tests
          # O caminho do artefato agora é relativo ao diretório de trabalho
          path: unit-tests-base-main/coverage

      - name: Derrubar contêineres
        if: always()
        run: docker compose -f docker-compose.test.yml down
