FROM node:22-alpine

# Definir diretório de trabalho
WORKDIR /app


# Copiar package.json e pnpm-lock.yaml
COPY package.json ./
COPY pnpm-lock.yaml ./

# Instalar pnpm globalmente
RUN npm install -g pnpm

# Instalar dependências com pnpm
RUN pnpm install --frozen-lockfile


# Copiar o restante do código
COPY . .

CMD ["pnpm", "run", "test:ci"]
